version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    ports:
      - "8082:8080"  # Mapea el puerto interno 8080 al 8082 de tu EC2
    environment:
      - AUTHENTICATION_API_KEY=08afc856-47a5-4a64-8750-4f5edb1bbc18
      - SERVER_PORT=8080
      - AUTO_RECONNECT=true
      - SAVE_SESSION=true
      - MULTI_DEVICE=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${EVOLUTION_POSTGRES_DB_NAME}
      - DATABASE_USER=${EVOLUTION_POSTGRES_DB_USER}
      - DATABASE_PASSWORD=${EVOLUTION_POSTGRES_DB_PASS}
    volumes:
      - evolution-data:/app/data
    restart: unless-stopped

volumes:
  evolution-data: