version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - AUTHENTICATION_API_KEY=08afc856-47a5-4a64-8750-4f5edb1bbc18
      - SERVER_PORT=8080
      - AUTO_RECONNECT=true
      - SAVE_SESSION=true
      - MULTI_DEVICE=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${EVOLUTION_POSTGRES_DB_NAME}
      - DATABASE_USER=${EVOLUTION_POSTGRES_DB_USER}
      - DATABASE_PASSWORD=${EVOLUTION_POSTGRES_DB_PASS}
    volumes:
      - evolution-data:/app/data
    restart: unless-stopped
    networks:
      - shared_network
volumes:
  evolution-data:
networks:
  shared_network:
    external: true