version: "3.9"

services:
  traefik:
    image: traefik:v3.5
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/dokploy/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/dokploy/traefik/dynamic
    networks:
      - dokploy
    restart: unless-stopped

  dokploy:
    image: dokploy/dokploy:latest
    env_file:
      - .env    
    environment:
      # Puerto del panel
      - PORT=3000

      # Usa TU Postgres externo (formato URL estándar de Postgres)
      # Las credenciales se obtienen automáticamente del archivo .env
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}

      # Usa TU Redis externo (host:puerto)
      - REDIS_HOST=${REDIS_HOST}:${REDIS_PORT}

      # (Opcional) Si quieres cambiar puertos que usa Traefik internamente
      - TRAEFIK_PORT=80
      - TRAEFIK_SSL_PORT=443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/etc/dokploy
      - docker_config:/root/.docker
    ports:
      - "3000:3000"
    depends_on:
      - traefik
    networks:
      - dokploy
    restart: unless-stopped

networks:
  shared_network:
    external: true

volumes:
  docker_config: {}
