version: "3.9"

services:
  traefik:
    image: traefik:v3.5
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/dokploy/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:8083"
      - "--entrypoints.websecure.address=:8443"
    ports:
      - "8083:8080"
      - "8443:8443"
      - "8443:8443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/dokploy/traefik/dynamic
    networks:
      - shared_network
    restart: unless-stopped

  dokploy:
    image: dokploy/dokploy:latest
    env_file:
      - .env    
    environment:
      # Puerto del panel
      - PORT=3000

      # URL externa para Dokploy (IMPORTANTE para proxy reverso)
      - DOKPLOY_URL=https://dokploy.innovatexiot.com
      - APP_URL=https://dokploy.innovatexiot.com
      - BASE_URL=https://dokploy.innovatexiot.com

      # Usa TU Postgres externo (formato URL estándar de Postgres)
      # Las credenciales se obtienen automáticamente del archivo .env
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}

      # Usa el Redis del proyecto n8n-hosting
      - REDIS_HOST=n8n-hosting-redis-1
      - REDIS_PORT=6379

      # (Opcional) Si quieres cambiar puertos que usa Traefik internamente
      - TRAEFIK_PORT=80
      - TRAEFIK_SSL_PORT=443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/etc/dokploy
      - docker_config:/root/.docker
    ports:
      - "3000:3000"
    depends_on:
      - traefik
    networks:
      - shared_network
    restart: unless-stopped

networks:
  shared_network:
    external: true

volumes:
  docker_config: {}
