api:
  dashboard: true
  insecure: true     # <— añade esto

log:
  level: DEBUG

entryPoints:
  web:
    address: ":8081"

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: dokploy-network
  file:
    directory: /dynamic
    watch: true
