version: '3.8'

services:
  odoo:
    image: odoo:16
    container_name: odoo
    environment:
      - HOST=postgres
      - USER=${CRM_POSTGRES_DB_USER}
      - PASSWORD=${CRM_POSTGRES_DB_PASSWORD}
      - DATABASE_NAME=${CRM_POSTGRES_DB}
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  odoo_data: