version: '3.8'

services:
  odoo:
    image: odoo:18
    env_file: .env
    container_name: odoo
    environment:
      - HOST=postgres
      - USER=${CRM_POSTGRES_DB_USER}
      - PASSWORD=${CRM_POSTGRES_DB_PASSWORD}
      - DATABASE_NAME=${CRM_POSTGRES_DB}
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo_data:/var/lib/odoo
    command: --longpolling-port=8072
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  odoo_data: